from wf.__init__ import *

nf_nf_core_atacseq(
    input=[
        SampleSheet(
            sample="Sample_6",
            fastq_1=LatchFile(
                "s3://latch-public/test-data/35929/Test_Dataset_Verified/Sample_6/Sample_6.Rep_1.R1.fastq.gz"
            ),
            fastq_2=LatchFile(
                "s3://latch-public/test-data/35929/Test_Dataset_Verified/Sample_6/Sample_6.Rep_1.R2.fastq.gz"
            ),
            replicate=1,
        ),
        SampleSheet(
            sample="Sample_6",
            fastq_1=LatchFile(
                "s3://latch-public/test-data/35929/Test_Dataset_Verified/Sample_6/Sample_6.Rep_2.R1.fastq.gz"
            ),
            fastq_2=LatchFile(
                "s3://latch-public/test-data/35929/Test_Dataset_Verified/Sample_6/Sample_6.Rep_2.R2.fastq.gz"
            ),
            replicate=2,
        ),
        SampleSheet(
            sample="Sample_1",
            fastq_1=LatchFile(
                "s3://latch-public/test-data/35929/Test_Dataset_Verified/Sample_1/Sample_1.Rep_1.R1.fastq.gz"
            ),
            fastq_2=LatchFile(
                "s3://latch-public/test-data/35929/Test_Dataset_Verified/Sample_1/Sample_1.Rep_1.R2.fastq.gz"
            ),
            replicate=1,
        ),
        SampleSheet(
            sample="Sample_1",
            fastq_1=LatchFile(
                "s3://latch-public/test-data/35929/Test_Dataset_Verified/Sample_1/Sample_1.Rep_2.R1.fastq.gz"
            ),
            fastq_2=LatchFile(
                "s3://latch-public/test-data/35929/Test_Dataset_Verified/Sample_1/Sample_1.Rep_2.R2.fastq.gz"
            ),
            replicate=2,
        ),
    ],
    genome_source="latch_genome_source",
    run_name="Test-1",
    read_length=50,
    aligner=Aligner.bowtie2,
    fasta=None,
    gtf=None,
    outdir=LatchOutputDir("latch:///ATAC_Seq_Test"),
    seq_center=None,
    with_control=False,
    email=None,
    multiqc_title=None,
    genome=None,
    latch_genome=Reference.hg19,
    gff=None,
    bwa_index=None,
    bowtie2_index=None,
    chromap_index=None,
    star_index=None,
    gene_bed=None,
    tss_bed=None,
    macs_gsize=None,
    blacklist=None,
    mito_name=None,
    save_reference=False,
    ataqv_mito_reference=None,
    clip_r1=None,
    clip_r2=None,
    three_prime_clip_r1=None,
    three_prime_clip_r2=None,
    trim_nextseq=None,
    skip_trimming=False,
    save_trimmed=False,
    keep_dups=False,
    keep_multi_map=False,
    bwa_min_score=None,
    save_unaligned=False,
    macs_fdr=None,
    macs_pvalue=None,
    save_macs_pileup=False,
    skip_peak_qc=False,
    skip_peak_annotation=False,
    skip_consensus_peaks=False,
    skip_deseq2_qc=False,
    skip_fastqc=False,
    skip_picard_metrics=False,
    skip_plot_profile=False,
    skip_plot_fingerprint=False,
    skip_igv=False,
    skip_multiqc=False,
    skip_qc=False,
    multiqc_methods_description=None,
)
